# This is a basic workflow to help you get started with Actions

name: Build LaTeX Document

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-full

      - name: Compile LaTeX
        run: pdflatex -interaction=nonstopmode -output-directory=output asr-summary.tex

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-document
          path: output/asr-summary.pdf
